export const DESTINATION_ACTION_TYPES = {
    GET_DESTINATIONS: 'GET_DESTINATIONS',
    GET_DESTINATIONS_SUCCESS: 'GET_DESTINATIONS_SUCCESS',
    GET_DESTINATIONS_FAILED: 'GET_DESTINATIONS_FAILED'
};

export const VEHICLES_ACTION_TYPES = {
    GET_VEHICLES: 'GET_VEHICLES',
    GET_VEHICLES_SUCCESS: 'GET_VEHICLES_SUCCESS',
    GET_VEHICLES_FAILED: 'GET_VEHICLES_FAILED'
};

export const FALCONE_ACTION_TYPES = {
    SEARCH_FALCONE: 'SEARCH_FALCONE',
    SEARCH_FALCONE_SUCCESS: 'SEARCH_FALCONE_SUCCESS',
    SEARCH_FALCONE_FAILED: 'SEARCH_FALCONE_FAILED'
};
