export const DESTINATION_ACTION_TYPES = {
    GET_DESTINATIONS: 'GET_DESTINATIONS',
    GET_DESTINATIONS_SUCCESS: 'GET_DESTINATIONS_SUCCESS',
    GET_DESTINATIONS_FAILED: 'GET_DESTINATIONS_FAILED'
};

export const VEHICLES_ACTION_TYPES = {
    GET_VEHICLES: 'GET_VEHICLES',
    GET_VEHICLES_SUCCESS: 'GET_VEHICLES_SUCCESS',
    GET_VEHICLES_FAILED: 'GET_VEHICLES_FAILED'
};

export const FALCONE_ACTION_TYPES = {
    FIND_FALCONE: 'FIND_FALCONE',
    FIND_FALCONE_SUCCESS: 'FIND_FALCONE_SUCCESS',
    FIND_FALCONE_FAILED: 'FIND_FALCONE_FAILED'
};

export const JOURNEY_ACTION_TYPES = {
    UPDATE_DESTINATION: 'UPDATE_DESTINATION',
    UPDATE_VEHICLE: 'UPDATE_VEHICLE'
};

export const TOKEN_ACTION_TYPES = {
    GET_TOKEN: 'GET_TOKEN',
    GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',
    GET_TOKEN_FAILED: 'GET_TOKEN_FAILED'
};

export const FIND_FALCONE_ACTION_TYPES = {
    FIND_FALCONE: 'FIND_FALCONE',
    FIND_FALCONE_SUCCESS: 'FIND_FALCONE_SUCCESS',
    FIND_FALCONE_FAILED: 'FIND_FALCONE_FAILED'
};
